image: node:carbon

stages:
  - build
  - test

cache:
  paths:
    - 048377247451.dkr.ecr.ap-southeast-1.amazonaws.com/devopsdemo

install_dependencies:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - arn:aws:s3:::codepipeline-ap-southeast-1-248631530371/MyDemoDeploymentGrou/BuildArtif/
test_with_lab:
  stage: test
  script: npm test
